# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the Pearson Chi-Squared statistic.
#' 
#' @name chisq_pearson
#' 
#' @param \code{d} The observed vector
#' @param \code{e} The expected vector
#' 
#' @return The computed value of the statistic
NULL

#' @name _chisq_test
#' @rdname chisq_test
NULL

#' Compute the Chi-Squared statistic for a given column, grouped by another column.
#' 
#' @description Computes (1 - p-value) * 100 for each group, using a
#' Chi-Squared statistic to obtain the p-value.
#' 
#' @param \code{values} The vector of values
#' @param \code{groups} The vector of groups, corresponding to the values
#' 
#' @return A numeric vector of the statistic values for each group, named by group.
#' @export
chisq_test <- function(values, groups) {
    .Call('_NemesisOutliers_chisq_test', PACKAGE = 'NemesisOutliers', values, groups)
}

#' Compute the size of a group from its counts.
#' 
#' @name group_size
#' 
#' @param \code{group} A map from the counts of the group
#' 
#' @return The size of the group
NULL

#' Find the largest count in a group.
#' 
#' @name max_group_count
#' 
#' @param \code{group} A map from the counts of the group
#' 
#' @return The size of the group
NULL

#' Compute the population and group counts for a vector of values and
#' corresponding vector of group identifiers.
#' 
#' @name counts
#' 
#' @param \code{values} The vector of values
#' @param \code{groups} The vector of groups, corresponding to the values
#' 
#' @return A std::pair where the first item is the map of value -> count for the population,
#' and the second item is the map of group -> value -> count for the groups.
NULL

#' @name  _entropy_disc
#' @rdname entropy_disc
NULL

#' Compute information entropy of the values in each group.
#'
#' @param \code{values} The vector of values
#' @param \code{groups} The vector of groups, corresponding to the values
#' @param \code{type} The type of ratio to compute: "normal" or "frequent"
#'
#' @return A numeric vector of the values for each group, named by group.
#' Entropy is maximal when all events are equaly probable.
#' Normalized entropy is also known as Efficiency. It is the computed entropy
#'    divided by the maximum possible entropy for N events = log(N)
#' See, eg, https://en.wikipedia.org/wiki/Entropy_(information_theory)
#' @export
entropy_disc <- function(values, groups, type) {
    .Call('_NemesisOutliers_entropy_disc', PACKAGE = 'NemesisOutliers', values, groups, type)
}

#' @name _graph_density
#' @rdname graph_density
NULL

#' Compute a value of the density of the links between the values in each
#' group.
#' 
#' @param \code{values} The vector of values
#' @param \code{groups} The vector of groups, corresponding to the values
#' 
#' @return A numeric vector of the values for each group, named by group.
#' @export
graph_density <- function(values, groups) {
    .Call('_NemesisOutliers_graph_density', PACKAGE = 'NemesisOutliers', values, groups)
}

#' Group a vector of values, using a corresponding group vector.
#' 
#' @name group
#' 
#' @param \code{value_col} The vector of values
#' @param \code{group_col} The vector of groups, corresponding to the values
#' 
#' @return A map from group -> vector of values
NULL

#' @name _uniq_cont
#' @rdname uniq_cont
NULL

#' Computes the ratio of the coefficient of variation for each group to the
#' population.
#' 
#' @param \code{values} The vector of values
#' @param \code{groups} The vector of groups, corresponding to the values
#' 
#' @return A numeric vector of the ratio values for each group, named by group.
#' @export
uniq_cont <- function(values, groups) {
    .Call('_NemesisOutliers_uniq_cont', PACKAGE = 'NemesisOutliers', values, groups)
}

#' @name _uniq_disc
#' @rdname uniq_disc
NULL

#' Compute a ratio of the discrete unique values in each group.
#' 
#' @param \code{values} The vector of values
#' @param \code{groups} The vector of groups, corresponding to the values
#' @param \code{type} The type of ratio to compute: "distinct" or "frequent"
#' 
#' @return A numeric vector of the values for each group, named by group.
#' @export
uniq_disc <- function(values, groups, type) {
    .Call('_NemesisOutliers_uniq_disc', PACKAGE = 'NemesisOutliers', values, groups, type)
}

